- name: 解压nginx第三方模块
  shell: cd {{ nginx_tmp_dir }} && tar -xzf {{ item }}
  with_items:
    - echo-nginx-module-0.61.tar.gz
    - headers-more-nginx-module-0.32.tar.gz
    - LuaJIT-2.0.4.tar.gz
    - lua-nginx-module-0.10.11.tar.gz
    - nginx-dav-ext-module-0.1.0.tar.gz
    - ngx_devel_kit-0.3.0.tar.gz
    - ngx_http_auth_pam_module-1.5.1.tar.gz
- name: Lua 的编译安装
  shell: "{{ item }}"
  with_items:
    - cd {{ nginx_tmp_dir }}/LuaJIT-2.0.4 && make && make install
    - echo "/usr/local/lib" > /etc/ld.so.conf.d/lua.conf
    - /sbin/ldconfig
    - echo "export LUAJIT_LIB=/usr/local/lib/" >> /etc/profile
    - echo "export LUAJIT_INC=/usr/local/include/luajit-2.0" >> /etc/profile
    - . /etc/profile
