- name: start nginx
  include_tasks: nginx_config/nginx_start_ver1.yml 
  when: ((ansible_distribution|lower == "centos" or ansible_distribution|lower == "redhat") and ansible_distribution_major_version != "7") or (ansible_distribution|lower == "ubuntu" and ansible_distribution_major_version == "12") or (ansible_distribution|lower == "ubuntu" and ansible_distribution_major_version == "14")

- name: start nginx
  include_tasks: nginx_config/nginx_start_ver3.yml
  when: ansible_distribution|lower == "ubuntu" and ansible_distribution_major_version == "16"
