---
- include_tasks: pack_dis.yml

- include_tasks: pre_install/install_php_dep_env_{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml

- include_tasks: install_php.yml
- include_tasks: php_config.yml
