- name: judge luajit exists
  shell: test ! -e /lib/x86_64-linux-gnu/libluajit-5.1.so.2
  register: result
- name: make soft link for luajit
  file: src=/usr/local/lib/libluajit-5.1.so.2.0.4 dest=/lib/x86_64-linux-gnu/libluajit-5.1.so.2 state=link
  when: result is success
